apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: message-board-app-migration-
spec:
  pipelineSpec:
    tasks:
      - name: message-board-task
        params:
          - name: source-context
            value: src
          - name: dest-context
            value: dest
          - name: dest-namespace
            value: message-board
          - name: source-namespace
            value: message-board
          - name: source-pvc-name
            value: message-board-data
          - name: endpoint-type
            value: route
          - name: dest-storage-class-name
            value: gp3
        taskRef:
          kind: Task
          name: crane-transfer-pvc
        workspaces:
          - name: kubeconfig
            workspace: kubeconfig
    workspaces:
      - name: kubeconfig
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: kubeconfig
      secret:
        secretName: kubeconfig
