apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: message-board-data
  labels:
    app: message-board
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
